### ISSUE TITLE
Glitch when moving the camera

### ISSUE THREAD

**Issue by aquintiliano** [RyanNielson/PixelCamera2D#1]
Hi, I'm using your lib, and it's really great, with a static camera, but when I need to move the camera to follow my character, a "glitch" occurs, it can be seen when I have many objects, it seems like each object can't move at same time, and sometimes they shake... have you seen it before?

**Comment by RyanNielson** [comment]
It doesn't sound familiar. If you could try to reproduce it and attach a simple project that shows the issue I may be able to take a look at it.

**Comment by aquintiliano** [comment]
I just added this code to camera, to move it, in your scene Main.unity, you will see the fallen tile moving weird

`public class MoveCamera: MonoBehaviour {
    void Update () {
        float velocity = 0.2f
        Vector3 newPosition = new Vector3 (transform.position.x + velocity, transform.position.y, transform.position.z);
        transform.position = Vector3.Lerp (transform.position, newPosition, Time.deltaTime);
    }
}`

**Comment by 5alamander** [comment]
May your texture size does not match the screen size,
I have 32*32 tiles, and I set PixelCamera2D.BaseHeight = 384 (which is 12 \* 32), and set the MainCamera.Size = 1.92 (the texture assets is 100 pixels per unit). It will move smoothly

**Comment by aquintiliano** [comment]
i`m gonna try it, but why 1.92? and I tested and saw this problem in your project... you tried it?

**Comment by 5alamander** [comment]
MainCamera.Size = 1.92, this means the Camera.Height is 1.92 \* 2 = 3.84 unit,
and all my textures are (100 pixels per unit),  so, the height is exactly 384 pixels,
and this can exactly contains 12 tiles in my project (which uses 32 \* 32 tiles).

You must calculate this value for your own project

notice:
- check it when the game is running.
- keep the 'Game Tab' size bigger than you project screen size(otherwise, the pixel size will be changed), or you can enable 'Maximize on play' directly.

forgive my awful English o(╯□╰)o ..................
